services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./api:/api
      - /api/bin
      - /api/obj
    environment:
      - ASPNETCORE_ENVIRONMENT=dev
      # Database config
      - Database__ConnectionString=mongodb://root:example@mongodb:27017
      - Database__DatabaseName=sensordb
      - Database__ConveyorCollection=conveyor_readings
      - Database__BakingCollection=baking_readings
      - Database__DoughCollection=dough_readings
      - Database__PackingCollection=packing_readings
      # MQTT config
      - Mqtt__BrokerHost=mqtt
      - Mqtt__BrokerPort=1883
      - Mqtt__ClientId=mqtt-listener
      - Mqtt__Username=
      - Mqtt__Password=
      - Mqtt__TopicConveyor=sensors/conveyor
      - Mqtt__TopicBaking=sensors/baking
      - Mqtt__TopicDough=sensors/dough
      - Mqtt__TopicPacking=sensors/packing
    depends_on:
      - mongo
      - mqtt
    command: dotnet run --urls=http://+:5000 --no-launch-profile
    
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./web:/web
      - /web/node_modules
    environment:
      - NODE_ENV=dev
    command: npm run dev -- --host

  mqtt:
    image: eclipse-mosquitto
    container_name: mqtt
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    volumes:
      - ./mqtt/config:/mosquitto/config:rw
      - ./mqtt/data:/mosquitto/data:rw
      - ./mqtt/log:/mosquitto/log:rw
    restart: unless-stopped

  mongo:
    image: mongo:8.0-noble
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: sensordb
    volumes:
      - ./mongo/data:/data/db

  # sensors:
  #   build:
  #     context: ./sensor
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - mqtt
  #   command: python run_all.py --broker mqtt --baking-furnaces 2 --conveyor-belts 1 --dough-mixers 1 --packing-lines 1